export const dataCard = {
  NAME: 'Nome:',
  AGE: 'Idade:',
  YEARS: 'anos',
  BIRTHDATE: 'Nascimento:',
  PHONE: 'Telefone:',
  NAMEFATHER: 'Pai:',
  NAMEMOTHER: 'Mãe:',
  PLAYER: 'Jogador do',
  POSITION: 'Posição',
  NATIONALITY: 'Nacionalidade:',
  BESTTEAM: 'É o melhor time que existe',
  BESTPLAYER: 'É o melhor jogador de todos os tempos',
  FRUIT: 'Fruta:',
  ADD: 'Com:',
  COUNTRY: 'País:',
  TEAMONE: 'Corinthians',
  TEAMTWO: 'Barcelona',
  TEAMTREE: 'Liverpool',
  TEAMFOUR: 'Borússia Dortmund',
  TEAMS: 'Time que eu Torço',
  TITLE: 'Esse é o meu projeto'
}